name: Build, Push, and Deploy
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set env
        run: echo "GITHUB_BRANCH=$(echo $GITHUB_REF_NAME-$GITHUB_SHA)" >> $GITHUB_ENV  

      - name: Build Docker image
        run: |
          docker login -u wohligakash -p dckr_pat_vxGVKHxz4zSshfCab0G3zEjegEA
          docker build -t wohligakash/skyyyyyyyyy:$GITHUB_REF_NAME-$GITHUB_SHA .
          docker push wohligakash/skyyyyyyyyy:$GITHUB_REF_NAME-$GITHUB_SHA
          
      - name: Update manifest file
        run: |
        
          
          # git clone https://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@github.com/swarajwohlig2107/sample-gitops.git
          git clone https://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@github.com/wohligakash/configmap-rnd-gitops.git --branch main

          # https://github.com/wohligakash/configmap-rnd-gitops.git
          cd configmap-rnd-gitops
          # git checkout main
          git config user.name "wohligakash"
          git config user.email "akash.pawar@wohlig.com"
          yq e '.spec.template.spec.containers[0].image = "wohligakash/skyyyyyyyyy:${{ env.GITHUB_BRANCH }}"' -i deployment.yaml
          git add .
          git commit -m "updating newer image"
          git push origin main
